#ifndef TEPTRIS_VERSION_H
#define TEPTRIS_VERSION_H

#define TEPTRIS_VERSION_MAJOR 0
#define TEPTRIS_VERSION_MINOR 1
#define TEPTRIS_VERSION_PATCH 15
#define TEPTRIS_VERSION_STRING "0.1.15"

#endif /* TEPTRIS_VERSION_H */
